export const SHOW_DETAILS="SHOW_DETAILS";
export const SHOW_DETAILS_ACTION="SHOW_DETAILS_ACTION";
export const SAVE_EDIT_DETAILS="SAVE_EDIT_DETAILS";
export const SAVE_EDIT_DETAILS_ACTION="SAVE_EDIT_DETAILS_ACTION";
export const SEARCH_TEXT="SEARCH_TEXT";
export const SEARCH_TEXT_ACTION="SEARCH_TEXT_ACTION";